Repository cloudposse/terraform-aws-rds-cluster, pull requests merged in 2024-12, with the labels that each got.

#242 Multiple cleanups
  README.md
  docs/terraform.md
  examples/complete/main.tf
  examples/postgres/main.tf
  examples/serverlessv2_postgres/main.tf
  main.tf
  test/src/Makefile
  test/src/go.mod
  variables.tf
Labels: bugfix, minor, needs-cloudposse

#244 fix: reserved instances restrictions
  main.tf
Labels: patch, bugfix

#248 fix: reserved instance multi_az setting
  main.tf
Labels: triage

#249 fix: reserved instances, aurora rds specifics
  main.tf
Labels: triage
